# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
JobStatus.create(name: "Active")
JobStatus.create(name: "Cancelled")
JobStatus.create(name: "Drybook")
JobStatus.create(name: "Complete")
JobStatus.create(name: "Job Complete")

JobType.create(name: "General Cleaning")
Franchise.create(name: "Chicago")
Franchise.create(name: "Tampa")
Franchise.create(name: "New York")

ReferralType.create(name: "Ad/TV")
ReferralType.create(name: "Friend")
ReferralType.create(name: "Other")

State.create(name: "AL")
State.create(name: "AK")
State.create(name: "AZ")
State.create(name: "AR")
State.create(name: "CA")
State.create(name: "CO")
State.create(name: "CT")
State.create(name: "DE")
State.create(name: "FL")
State.create(name: "GA")
State.create(name: "HI")
State.create(name: "ID")
State.create(name: "IL")
State.create(name: "IN")
State.create(name: "IA")
State.create(name: "KS")
State.create(name: "KY")
State.create(name: "LA")
State.create(name: "ME")
State.create(name: "MD")
State.create(name: "MA")
State.create(name: "MI")
State.create(name: "MN")
State.create(name: "MS")
State.create(name: "MO")
State.create(name: "MT")
State.create(name: "NE")
State.create(name: "NV")
State.create(name: "NH")
State.create(name: "NJ")
State.create(name: "NM")
State.create(name: "NY")
State.create(name: "NC")
State.create(name: "ND")
State.create(name: "OH")
State.create(name: "OK")
State.create(name: "OR")
State.create(name: "PA")
State.create(name: "RI")
State.create(name: "SC")
State.create(name: "SD")
State.create(name: "TN")
State.create(name: "TX")
State.create(name: "UT")
State.create(name: "VT")
State.create(name: "VA")
State.create(name: "WA")
State.create(name: "WV")
State.create(name: "WI")
State.create(name: "WY")
