class Ticsheet < ActiveRecord::Base
  def self.water_damage_list
    array = [['8010', 'Emerg Service, After HR/Wknd', 'EA'],
             ['8020', 'Emerg Service, Holiday Job', 'EA'],
             ['8200', 'Debris, Disposal', 'BAG'],
             ['8210', 'Debris, Disposal', 'LD'],
             ['9485', 'Labor, General', 'HR'],
             ['9505', 'Labor, On Site Supervision', 'HR'],
             ['1000', 'Ceiling, Remove', 'SF'],
             ['1020', 'Acoustical Tile, Remove', 'SF'],
             ['1030', 'Acoustical Tile Grid, Remove', 'SF'],
             ['1220', 'Insulation, Remove', 'SF'],
             ['1155', 'Ceiling, Antimicrobial', 'SF'],
             ['1155', 'Ceiling, EPA Reg. Disinfectant', 'SF'],
             ['2010', 'Walls, Remove', 'SF'],
             ['1220', 'Insulation, Remove', 'SF'],
             ['2080', 'Wall, EPA Reg. Disinfectant', 'SF'],
             ['2090', 'Wall, Antimicrobial', 'SF'],
             ['3390', 'Carpet, Clean', 'SF'],
             ['3390', 'Carpet, Antimicrobial Pretreat', 'SF'],
             ['3390', 'Carpet, Extraction', 'SF'],
             ['3390', 'Carpet, Extraction, Black', 'SF'],
             ['3390', 'Carpet, Extraction, Gray', 'SF'],
             ['3390', 'Carpet, Extraction, Heavy', 'SF'],
             ['3390', 'Carpet, Antimicrobial', 'SF'],
             ['3390', 'Carpet, Lift', 'SF'],
             ['3390', 'Remove/Cut & Bag', 'SF'],
             ['3390', 'Heavy Soil, Clean', 'SF'],
             ['3390', 'Floor, Clean', 'SF'],
             ['3390', 'Floor, EPA Reg. Disinfectant', 'SF'],
             ['3390', 'Floor, Extraction', 'SF'],
             ['3390', 'Floor, Extraction, Heavy', 'SF'],
             ['3390', 'Floor, Antimicrobial', 'SF'],
             ['3390', 'Floor, Remove', 'SF'],
             ['3390', 'Floor, Hardwood, Clean', 'SF'],
             ['3390', 'Floor, Subfloor, Clean', 'SF'],
             ['3390', 'Floor, Vinyl, Extraction', 'SF'],
             ['3390', 'Floor, Vinyl, Remove', 'SF'],
             ['3390', 'Pad, Remove', 'SF'],
             ['3390', 'Steps, Clean', 'EA'],
             ['3390', 'Steps, Attic, Clean', 'EA'],
             ['3390', 'Steps, Carpeted, Clean', 'EA'],
             ['3390', 'Steps, Hard Surface, Clean', 'EA'],
             ['3390', 'Tackless Strip Remove', 'LF'],
             ['3390', 'Steps, Carpeted, Antimicrobial', 'EA'],
             ['3390', 'Rug, Area, Antimicrobial', 'SF'],
             ['3390', 'Trim, Baseboard, Remove', 'LF'],
             ['3390', 'Trim, Remove', 'LF'],
             ['3390', 'Duct System, Int., Clean', 'EA'],
             ['3390', 'Duct System, Per Opening, Clean', 'EA'],
             ['3390', 'Duct System, Per Register, Clean', 'EA'],
             ['3390', 'Equipment, Setup & Take down', 'EA'],
             ['3390', 'Equipment, Monitor', 'DAY'],
             ['3390', 'Equipment, Clean', 'EA'],
             ['3390', 'Equipment, Decontamination', 'EA'],
             ['3390', 'Air Movers(S), Drying', 'DAY'],
             ['3390', 'Dehumidifier, Small', 'DAY'],
             ['3390', 'Dehumidifier, Larger', 'DAY'],
             ['3390', 'Dehumidifier, Desiccant', 'DAY'],
             ['3390', 'Air Scrubbers, <750 cfm', 'DAY'],
             ['3390', 'Air Scrubbers, 750> cfm', 'DAY'],
             ['3390', 'Personal Protective Eqiup.', 'EA'],
             ['3390', 'Pump, Rental', 'DAY'],
             ['3390', 'Pump, Rental', 'HR'],
             ['3390', 'Generator, Temp Power Contents', 'DAY'],
             ['3390', 'Furniture/Contents - Manipulation', 'HR']
           ]
    return array
  end
end
